### ISSUE TITLE
Wrong drawing when the nodes are declared first (graphviz)

### ISSUE THREAD

**Issue by bew** [ironcamel/Graph-Easy#4]
Using:
```dot
digraph {
  rankdir="LR"

  foo
  bar [label="bar-label!"]
  baz

  {foo bar} -> baz
}
```
The output is:
```
                     +--+
                     v  |
+------------+     +------+     +-----+
| bar-label! | --> | baz  | <-- | foo |
+------------+     +------+     +-----+
```
Which is wrong, `baz` does not have a link to itself...
The graphviz image: (made with `dot -Tpng`)
![noname](https://user-images.githubusercontent.com/9730330/83078505-1101b400-a07a-11ea-9fa0-dbf699a7b038.png)

Note: if I don't declare the nodes beforehand:
```dot
digraph {
  rankdir="LR"
  {foo bar} -> baz
}
```
I get the correct graph:
```
+-----+     +-----+     +-----+
| bar | --> | baz | <-- | foo |
+-----+     +-----+     +-----+
```

**Comment by ironcamel** [comment]
@bew thanks but this is not the official repo for Graph::Easy. I do not have permissions to update this module on CPAN. You can find info about the official repo and bug tracker here: https://metacpan.org/release/Graph-Easy
The author is @shlomif https://metacpan.org/author/SHLOMIF
